### ISSUE TITLE
[DataCap Application] <chenggong> 

### ISSUE THREAD

**Issue by zoufang567653** [Storify-LLC/Storify-Data-Pathway#19]
### Version

1

### DataCap Applicant

Zoufang

### Project ID

18

### Data Owner Name

HZ chenggong

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.chenggong.pro/

### Social Media Handle

http://www.chenggong.pro/

### Social Media Type

Other

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1470TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f16ystbzcbi7i2hskdkhpksvnjn2anhwxzksualmi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founed in 2019,ChengGong(Hangzhou)Cultural Media is a film and television cultural communication team dedicated to brand strategy services, new media development and operation,film and television filming and production and live streaming pushing services
on various platforms.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Campus class filming,product filming,VR panorama filming,image promo,large outdoor performance events,short video filming,etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.chenggong.pro/page 16
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03226688 
f03239692
f03219700
f03219702
f01106668  
f01315096   
f0870558     
f03055005   
f03055018   
f03055029   
f01518369   
f01889668
f03202108
f03239692
f03254235
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by zoufang567653** [comment]
<img width="935" alt="image" src="https://github.com/user-attachments/assets/e4fad1f0-04e1-4fb0-843d-57987438c123">

Why didn't it automatically trigger a bot review? @kacperzuk-neti  @willscott

**Comment by zoufang567653** [comment]
Sorry man @kacperzuk-neti @willscott , any updation ？Thank you very much！

**Comment by zoufang567653** [comment]
checker:manualTrigger

**Comment by ChrisDracula** [comment]
1.Have you prepared enough token for sector pledge?
2.Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
3.How will the data be prepared? Please include tooling used and technical details
4.If you are not preparing the data, who will prepare the data? (Name and Business)
5.Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
6.Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by zoufang567653** [comment]
Thank you for your reply.
1. Yes, SPs have already prepared at least 80% of the Filecoin collateral.
2. We are data preparers, mainly using official tools for data preparation, such as Boost, Lotus, and Singularity.
3. Yes, this is the first storage attempt, at least for these SPs.
4. Most of the SPs have been listed on the application form, and we plan to collaborate with these SPs in the first round:
   - f03202108 (Hong Kong)
   - f03239692 (Frankfurt)
   - f03254235 (London)

**Comment by ChrisDracula** [comment]
The data sample is limited. Can you provide more data to support the large-scale application?

**Comment by ChrisDracula** [comment]
It looks like the credibility is good. For the first round, according to the rules, I will support 768 TiB. Please meet the Spark retrieval rate requirements.

**Comment by zoufang567653** [comment]
Early disclosure, the first batch of cooperating SPs: f03179570, f03179572, f03214937, f03229932, f03229933, f03231117, f03231121

**Comment by zoufang567653** [comment]
checker:manualTrigger

**Comment by shizhigu** [comment]
<img width="616" alt="b66fa9214c556c887e50ee45972f956" src="https://github.com/user-attachments/assets/43fbbb1c-72c9-4cd7-abd3-7ae0c220a2cc" />
Please explain why data sharing occurs?

**Comment by zoufang567653** [comment]
We apologize for the inconvenience. Upon investigation, we found that we mistakenly issued 7.9 TiB of data repeatedly due to an oversight on our part during the distribution process. We assure you that we have taken measures to prevent this from happening again. Thank you for your continued support.

**Comment by shizhigu** [comment]
7.75 TiB of data sharing is too much for the allocator, and we are unable to proceed with the next round of quota approvals. We welcome you to reapply to us once you have found a new data customer.
