### ISSUE TITLE
[DataCap Application] <Xuet> - <Xuet>

### ISSUE THREAD

**Issue by winter0707winter** [Storify-LLC/Storify-Data-Pathway#3]
### Version

1

### DataCap Applicant

winter

### Project ID

2

### Data Owner Name

Xuet

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.xuetian.cn/

### Social Media Handle

https://www.xuetian.cn/

### Social Media Type

Other

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

950

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1000TiB

### On-chain address for first allocation

f1oq5ghq2ctqhwgnjttgwnnlxc4ujikmhlks2jwsa

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its founding in 2010, Xuetian Education has become a multi-disciplinary, comprehensive and professional education platform enterprise integrating training and teaching, educational product development, and vocational skills training by virtue of its professional, leading and trustworthy teaching and training services. At present, it has opened more than 90 branches in Hangzhou, Beijing, Shanghai, Guangzhou, Shenzhen, Xi'an, Nanjing, Hefei, Zhengzhou, Shenyang, Jinan and other key cities across the country, serving hundreds of thousands of students every year, with a cumulative total of more than one million students, and tens of thousands of enterprises in various industries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mainly educational videos, training videos, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://www.xuetian.cn/open-class
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03000070
f03074583  
f03074586   
f03074587   
f03074589   
f03074592
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by shizhigu** [comment]
Thank you for opening this issue. Could you please provide more information to help us better understand the situation?

1. Are you a data preparer? How will the data be prepared? Please include tooling used and technical details.
2. Please disclose information on SP cooperation?
3. Are the pledged coins sufficiently prepared? When do you plan to start storage?

**Comment by winter0707winter** [comment]
Dear official allocator, thanks for the review!
1. As a deep filecoin enthusiast, I am very optimistic about the future development of IPFS, and I have been quite experienced in data preparation, mainly through the official filecoin tools boost and Lotus;
2. the basic situation of the SPs we are currently communicating with is as follows, we will also try to contact more SPs
f03074583 Tokyo Fly
f03074589 HongKong Xing
f03074586 HongKong Datastone
f03074587 Seoul Hanku
f03000070 China Honglian Tec
f03074592 USA HKblockchain
3. The contacted SPs have committed to have at least 80% of the pledged coins ready and plan to start storing them in late June or early July.

**Comment by shizhigu** [comment]
Looks good, willing to support in the first round.

**Comment by shizhigu** [comment]
Due to a mistake, please submit again, thank you.

**Comment by winter0707winter** [comment]
ok，I'll start a new application later.
