### ISSUE TITLE
[DataCap Application] <OpenData> - <CloudOptimized>

### ISSUE THREAD

**Issue by dos2un1x** [Storify-LLC/Storify-Data-Pathway#7]
### Version

1

### DataCap Applicant

dos2un1x

### Project ID

1

### Data Owner Name

Element 84

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

www.element84.com

### Social Media Handle

https://www.element84.com/blog/

### Social Media Type

Other

### What is your role related to the dataset

Other

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

16.4PiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1iffzvo7naezyxyir3ylyma37fves66oah2endxa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Sentinel-2 mission is a land monitoring constellation of two satellites that provide high resolution optical imagery and provide continuity for the current SPOT and Landsat missions. The mission provides a global coverage of the Earth's land surface every 5 days, making the data of great use in ongoing studies. This dataset is the same as the Sentinel-2 dataset, except the JP2K files were converted into Cloud-Optimized GeoTIFFs (COGs). Additionally, SpatioTemporal Asset Catalog metadata has were in a JSON file alongside the data, and a STAC API called Earth-search is freely available to search the archive. This dataset contains all of the scenes in the original Sentinel-2 Public Dataset and will grow as that does. L2A data are available from April 2017 over wider Europe region and globally since December 2018.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
https://registry.opendata.aws/sentinel-2-l2a-cogs
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sentinel-cogs/
s3://sentinel-cogs/(16.4 PiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Others

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1.f02837226 UK
2.f02864300 US
3.f02894286 KR
4.f02870401 ID
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by dos2un1x** [comment]
Dear @shizhigu @ChrisDracula ,
We want to store public data in filcoin .
Have left message in your wechat .
Feel free to contact me with any questions .

Thank you!

**Comment by shizhigu** [comment]
Thank you for opening this issue, I want to ask you some questions.
Is this your first time to apply? 
Can you confirm that you will follow the Fil+ guideline?
Do you have enough token for your plan?
Is SPs ready? Are the pledged coins sufficiently prepared? When do you plan to start storage?

**Comment by ChrisDracula** [comment]
I see that you only have 4 miners to store, can you find more miners to store the replicas? If there are more miners, please list the miner.

**Comment by dos2un1x** [comment]
> Thank you for opening this issue, I want to ask you some questions. Is this your first time to apply? Can you confirm that you will follow the Fil+ guideline? Do you have enough token for your plan? Is SPs ready? Are the pledged coins sufficiently prepared? When do you plan to start storage?

Is this your first time to apply?
No, I've had experience.
Can you confirm that you will follow the Fil+ guideline?
Yes, I will.
Do you have enough token for your plan?
Enough tokens have been prepared.
Is SPs ready? Are the pledged coins sufficiently prepared? When do you plan to start storage?
SPs is ready. 
Start this project anytime.

**Comment by dos2un1x** [comment]
> I see that you only have 4 miners to store, can you find more miners to store the replicas? If there are more miners, please list the miner.

More sps are in the pipeline and will be reported back to you when they are ready.

**Comment by ChrisDracula** [comment]
We are willing to support the first round, and we hope you can find more miners in the future. If you cannot find more than 5, we will control the approval quota for the next round.

**Comment by dos2un1x** [comment]
> We are willing to support the first round, and we hope you can find more miners in the future. If you cannot find more than 5, we will control the approval quota for the next round.

We will use 2 SP in the first round, and then gradually increase to 5.
Thank you for your signatures.
We will start the project as soon as possible.

**Comment by dos2un1x** [comment]
checker:manualTrigger

**Comment by dos2un1x** [comment]
Dear @shizhigu @ChrisDracula ,
We have completed the first round, now apply for the second round, the report is normal.
Please feel free to contact me if you have any questions.

**Comment by shizhigu** [comment]
The report appears to be in order.  
The next round 512T will be approved, please update SPs changes in time.

**Comment by shizhigu** [comment]
checker:manualTrigger

**Comment by shizhigu** [comment]
checker:manualTrigger

**Comment by shizhigu** [comment]
Shocking encapsulation report! I will strictly intervene in further issuance of Datacap.

1. client did not follow the communication process, honestly and truthfully for the number of SPs improvement, only 2 SPs from the beginning to now, despite the secondary allocation we took the limited approval amount. client's behavior is against the principle of filecoin's maximizing trust.

2. Please provide a convincing explanation for the following:
⚠️ 1 storage providers sealed more than 50% of total datacap - f02894286: 50.09%
⚠️ 100.00% of Storage Providers have retrieval success rate less than 75%.
⚠️ The average retrieval success rate is 1.71%

3. If I don't receive a formal and reasonable explanation within the next week, can the official governance team let me know how to respond, @Kevin-FF-USA, so that I can retrieve the Datacap that has already been approved?

**Comment by shizhigu** [comment]
No response has been received and I will stop the approval of this application application and close it manually with the end of the month.
